In [32]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

In [33]:
# Create Dataset
data = {
    "Study_Hours":[1,2,3,4,5,6,7,8,9,10,11,12],
    "Attendance":[60,65,70,72,75,80,82,85,88,90,92,95],
    "Assignments":[2,3,4,5,5,6,7,7,8,8,9,10],
    "Marks":[35,40,45,50,58,65,72,78,82,88,92,96]
}
df=pd.DataFrame(data)

In [34]:
 #part 1                # Saving CSV
df.to_csv("student_performance.csv", index=False)

In [35]:
# Loading  Dataset
df = pd.read_csv("student_performance.csv")

# First 5 rows
df.head(5)

   Study_Hours  Attendance  Assignments  Marks
0            1          60            2     35
1            2          65            3     40
2            3          70            4     45
3            4          72            5     50
4            5          75            5     58

In [36]:
df.tail(5)     # last 5 rows

    Study_Hours  Attendance  Assignments  Marks
7             8          85            7     78
8             9          88            8     82
9            10          90            8     88
10           11          92            9     92
11           12          95           10     96

In [37]:
df.shape
df.columns
df.dtypes

Study_Hours    int64
Attendance     int64
Assignments    int64
Marks          int64
dtype: object

In [38]:
df.describe()

       Study_Hours  Attendance  Assignments      Marks
count    12.000000   12.000000    12.000000  12.000000
mean      6.500000   79.500000     6.166667  66.750000
std       3.605551   11.172206     2.443296  21.080474
min       1.000000   60.000000     2.000000  35.000000
25%       3.750000   71.500000     4.750000  48.750000
50%       6.500000   81.000000     6.500000  68.500000
75%       9.250000   88.500000     8.000000  83.500000
max      12.000000   95.000000    10.000000  96.000000

In [39]:
X = df[["Study_Hours","Attendance","Assignments"]]

y = df["Marks"]

print("Features:")
print(X)

print("\nLabel:")
print(y)

Features:
    Study_Hours  Attendance  Assignments
0             1          60            2
1             2          65            3
2             3          70            4
3             4          72            5
4             5          75            5
5             6          80            6
6             7          82            7
7             8          85            7
8             9          88            8
9            10          90            8
10           11          92            9
11           12          95           10

Label:
0     35
1     40
2     45
3     50
4     58
5     65
6     72
7     78
8     82
9     88
10    92
11    96
Name: Marks, dtype: int64

In [40]:
#part 4
#Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (9, 3)
X_test: (3, 3)
y_train: (9,)
y_test: (3,)

In [41]:
#part--5    Train our model
model = LinearRegression()

model.fit(X_train, y_train)

print("\nCoefficients:", model.coef_)
print("\nIntercept:", model.intercept_)

Coefficients: [ 3.45487968  1.34491979 -2.40274064]

Intercept: -48.100601604278054

What is the slope?

The slope is represented by the coefficient values returned by model.coef_. Each coefficient shows how much the marks change when a feature increases by one unit while keeping other features constant.

What is the intercept?

The intercept is the starting value of the prediction when all feature values are zero.

What do they mean?

The coefficients indicate feature importance and direction of impact. Positive coefficients mean marks increase as the feature increases. The intercept acts as the baseline prediction.

In [42]:
#part -6
#predictions
new_students = pd.DataFrame({
    "Study_Hours":[5,8,12],
    "Attendance":[80,90,95],
    "Assignments":[5,8,10]
})

predictions = model.predict(new_students)

for i,pred in enumerate(predictions):
    print(f"Student {i+1}: {pred:.2f}")

Student 1: 64.75
Student 2: 81.36
Student 3: 97.10

In [43]:
# part-7
#Actual vs Preditions
pred_test = model.predict(X_test)

comparison = pd.DataFrame({
    "Actual Marks": y_test,
    "Predicted Marks": pred_test
})

comparison["Difference"] = abs(
    comparison["Actual Marks"] -
    comparison["Predicted Marks"]
)

print(comparison)

max_error = comparison["Difference"].max()

print("\nHighest Prediction Error:", max_error)

    Actual Marks  Predicted Marks  Difference
10            92        92.011029    0.011029
9             88        88.269051    0.269051
0             35        31.243984    3.756016

Highest Prediction Error: 3.7560160427807574

The student with the highest value in the Difference column has the highest prediction error.

In [44]:
# Model evaluation
mae = mean_absolute_error(y_test, pred_test)
r2 = r2_score(y_test, pred_test)

print("MAE:", mae)
print("R² Score:", r2)

MAE: 1.3453654188948245
R² Score: 0.9929962957709836

What is MAE?

Mean Absolute Error measures the average absolute difference between actual and predicted values. Lower MAE indicates better model performance.

What is R² Score?

R² Score measures how well the model explains the variation in the target variable. Values closer to 1 indicate a better fit.

Is the model performing well?

Yes. If MAE is low and R² is close to 1, the model is performing well.

In [45]:
#part--9
#plotly Visualizations
#Plot 1: Study Hours vs Marks
import plotly.express as px

fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    title="Study Hours vs Marks"
)

fig.show()

In [46]:
#Plot 2: Attendance vs Marks
fig = px.scatter(
    df,
    x="Attendance",
    y="Marks",
    hover_data=df.columns,
    title="Attendance vs Marks"
)

fig.show()

In [47]:
 #Plot 3: Assignments vs Marks
 fig = px.scatter(
    df,
    x="Assignments",
    y="Marks",
    color="Assignments",
    title="Assignments vs Marks"
)

fig.show()

In [48]:
#Plot 4: Regression Line Visualization
fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    trendline="ols",
    title="Regression Line"
)

fig.show()

In [49]:
#Plot 5: Predicted Marks Trend
future = pd.DataFrame({
    "Study_Hours": list(range(1,16)),
    "Attendance": [85]*15,
    "Assignments": [7]*15
})

future["Predicted Marks"] = model.predict(future)

fig = px.line(
    future,
    x="Study_Hours",
    y="Predicted Marks",
    title="Predicted Marks Trend"
)

fig.show()

In [50]:


house_data = {
    "Area_sqft":[800,900,1000,1100,1200,1300,1400,1500,1600,1700,
                 1800,1900,2000,2100,2200,2300,2400,2500,2600,2700],

    "Bedrooms":[1,2,2,2,3,3,3,3,4,4,
                4,4,5,5,5,5,6,6,6,6],

    "Age":[20,18,17,15,14,12,10,9,8,7,
           6,5,5,4,4,3,3,2,2,1],

    "Price":[2000000,2300000,2600000,2900000,3300000,
             3600000,3900000,4200000,4600000,4900000,
             5300000,5600000,6000000,6400000,6800000,
             7200000,7600000,8000000,8400000,8800000]
}

df = pd.DataFrame(house_data)

print(df.head())

   Area_sqft  Bedrooms  Age    Price
0        800         1   20  2000000
1        900         2   18  2300000
2       1000         2   17  2600000
3       1100         2   15  2900000
4       1200         3   14  3300000

In [51]:
df.to_csv("house_price_prediction.csv", index=False)

In [52]:
X = df[["Area_sqft", "Bedrooms", "Age"]]

y = df["Price"]

print("Features:")
print(X.head())

print("\nLabel:")
print(y.head())

Features:
   Area_sqft  Bedrooms  Age
0        800         1   20
1        900         2   18
2       1000         2   17
3       1100         2   15
4       1200         3   14

Label:
0    2000000
1    2300000
2    2600000
3    2900000
4    3300000
Name: Price, dtype: int64

In [53]:
## train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train Shape:", X_train.shape)
print("X_test Shape:", X_test.shape)
print("y_train Shape:", y_train.shape)
print("y_test Shape:", y_test.shape)

X_train Shape: (16, 3)
X_test Shape: (4, 3)
y_train Shape: (16,)
y_test Shape: (4,)

In [54]:
# testing using  LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

Coefficients: [ 4238.2216539   -676.88715304 67898.12871512]
Intercept: -2758055.698407621

In [55]:
#predictions data
predictions = model.predict(X_test)

comparison = pd.DataFrame({
    "Actual Price": y_test,
    "Predicted Price": predictions
})

comparison["Difference"] = abs(
    comparison["Actual Price"] -
    comparison["Predicted Price"]
)

print(comparison)

    Actual Price  Predicted Price    Difference
0        2000000     1.989807e+06  10192.688136
17       8000000     7.969233e+06  30766.629139
15       7200000     7.190164e+06   9835.944051
1        2300000     2.277156e+06  22843.667329